### ISSUE TITLE
Is it possible to consider the case where `destroyCancellationToken` of `MonoBehaviour` does not work?

### ISSUE THREAD

**Issue by hekk-naoya-kishimoto** [Cysharp/R3#104]
If use `destroyCancellationToken` of `MonoBehaviour` in `AddTo()` when subscribing,
If the `GameObject` is left inactive and destroyed, `destroyCancellationToken` will not work and will not be unsubscribed.

In the case of `UniRx`, there is consideration for the case where `OnDestory()` is not called, but is it possible to take the same consideration in `R3`...?

https://github.com/neuecc/UniRx/blob/7cce378b3f8c8943b4cac8e847bdbb8e2e1802d1/Assets/Plugins/UniRx/Scripts/UnityEngineBridge/LifetimeDisposableExtensions.cs#L30

**Comment by neuecc** [comment]
Initially, there were no plans to create something like a Trigger, so it was completely excluded from the functionality, but since a Trigger has been added, it might be a good idea to add monitoring to AddTo(MonoBehavior).
Thank you.

**Comment by neuecc** [comment]
I've implemented, it includes in 1.0.0.
