### ISSUE TITLE
Very interesting library. but...

### ISSUE THREAD

**Issue by SuperJMN** [Cysharp/R3#106]
Very interesting library. What I fear the most is making compatible versions of RxUI and DynamicData, libraries that I use INTENSIVELY. 
Without them working, I'm out of luck.

My suggestion is that you could talk with major library owners to make compatible versions so end devs like me could use R3 instead. 
Anyways, heep up the good work! 

I wish you luck.

**Comment by neuecc** [comment]
GPT
AsSystemObservable and ToObservable support conversion to and from standard Rx, so it's not completely unusable.
However, it's undoubtedly difficult to use.
In R3, we have ReactiveProperty for UI support and ObservableCollections for collections,
but these are entirely different from ReactiveUI or DynamicData, so they cannot serve as a migration guide.
If R3 becomes widely used, there's a great chance it will be supported!
So, please start using R3 and help spread the word!
