### ISSUE TITLE
How to debug reactive streams in R3?

### ISSUE THREAD

**Issue by HedgehogNSK** [Cysharp/R3#109]
Hello. I use UniRx last several years. And now I'm trying get into R3.
I read the documentation. But I couldn't find alternative that I can use for .Debug method from now on.
How can we get logs of stream lifetime events like onSubscribe, onNext and onCompleted?
ObservableTracker doesn't look like it is what I'm looking for, does it?

Excuse me please if bugtracker isn't a right place to ask such questions. I just don't know where I have to ask them.
Thank you :)

**Comment by neuecc** [comment]
I do not intend to add something that directly corresponds to Debug, but you can create your own using Do.

```csharp
public static Observable<T> Debug<T>(this Observable<T> source, string label = null)
{
#if DEBUG
    var l = (label == null) ? "" : "[" + label + "]";
    return source
        .Do(
            onNext: x => UnityEngine.Debug.Log(l + "OnNext(" + x + ")"),
            onErrorResume: x => UnityEngine.Debug.Log(l + "OnErrorResume(" + x + ")"),
            onCompleted: x => UnityEngine.Debug.Log(l + "OnCompleted(" + x + ")"),
            onSubscribe: () => UnityEngine.Debug.Log(l + "OnSubscribe"),
            onDispose: () => UnityEngine.Debug.Log(l + "OnDispose"));
#else
    return source;
#endif
}
```
