### ISSUE TITLE
[Feature Request] Add documentation site

### ISSUE THREAD

**Issue by filzrev** [Cysharp/R3#113]
Are there any plans to add a documentation page?

It seems some Cysharp organization repositories have [docfx](https://github.com/dotnet/docfx)-based documentation.
And published to GitHub Pages.

**List of Cysharp's published sites**
|                    |                                                                 |
|--------------|--------------------------------------------|
| UniTask        | https://cysharp.github.io/UniTask/         |
| MagicOnion | https://cysharp.github.io/MagicOnion/ |

I’ve tried to create docfx-based site generation on `cloned repository`.
And it seems to work almost well.

**Demo site**
- Site Home: https://filzrev.github.io/R3/
- Copy of Readme content: https://filzrev.github.io/R3/articles
- API Page:  https://filzrev.github.io/R3/api/R3.html
- File Changes: https://github.com/filzrev/R3/commit/1735d714bb4259211e0cb4078ffba574199265ff

> [!NOTE] 
> Cysharp's docfx-based sites are using `DocfxTemplate` (https://github.com/Cysharp/DocfxTemplate)
> But it's not compatible with latest version of docfx template (`modern` template)
> So it may needs to adjust styles.

**Required steps to enable GitHub Actions based pages deployment **

1. Enable GitHub Actions based Pages deployment  
   from following setting page.  
   https://github.com/Cysharp/R3/settings/pages
2. Change settings at`About` on right navigation.
   And enable `Use your GitHub Pages website` setting.

**Comment by neuecc** [comment]
Thank you, I will consider it (after modifying DocfxTemplate).

**Comment by egil** [comment]
Instead of documentation on a website, I strongly prefer just having codedocs added. That way the documentation is available right in the code/editor.
