### ISSUE TITLE
After installing R3 via git URL, I have nearly 400 compilation errors with R3 in my Unity3d project. 

### ISSUE THREAD

**Issue by xuzimianxzm** [Cysharp/R3#131]
After installing R3 via git URL, I have nearly 400 compilation errors with R3 in my Unity3d project. It seems that it is caused by not being able to find the classes under the path "https://github.com/Cysharp/R3/tree/main/src/R3" in your project.

**Comment by neuecc** [comment]
Read about the Install process.
https://github.com/Cysharp/R3#unity
Perhaps you are not installing via NuGet.

**Comment by xuzimianxzm** [comment]
> Read about the Install process. https://github.com/Cysharp/R3#unity Perhaps you are not installing via NuGet.

Thank you for help. 
Of course I also tried the Nuget installation  in the trial documentation and it worked fine. But I still prefer to install them through git by url.
