### ISSUE TITLE
Add Observable.WhenAllAsync and Observable.WhenAnyAsync

### ISSUE THREAD

**Issue by euglenach** [Cysharp/R3#135]
The `Observable.WhenAll` from UniRx is gone in R3, can it be implemented as an asynchronous method that returns Task?

I had no choice but to create and use the following method as a replacement.
```csharp
public static Task<T[]> WhenAllAsync<T>(this IEnumerable<Observable<T>> sources, CancellationToken cancellationToken = default)
{
    return Task.WhenAll(sources.Select(s => s.LastAsync(cancellationToken)));
}
```

Also, can we implement `WhenAny`, which was not in UniRx?

thanks.

**Comment by neuecc** [comment]
R3 is designed not to "generate" or "handle" a single observable.
`IEnumerable<Observable<T>>` should be generated as `IEnumerable<Task<T>>`, and you should use Task.WhenAll.
Of course, it's good to use something like LastAsync for conversion along the way, but this conversion should occur relatively early in the code, and by the time you get to method return values, they should be represented as Tasks.
