### ISSUE TITLE
Type or namespace name Observable<> could not be found

### ISSUE THREAD

**Issue by tattyd** [Cysharp/R3#136]
Hi there,

Thank you for your work!

I added R3 to my Unity project via the Git URL.

I also added `R3.Unity` to my main assembly definition file, as an assembly definition reference.

However, I still get about 400 compilation errors in the console, all of which some variant of this (3 examples below):

```
Library\PackageCache\com.cysharp.r3@4184a1734e\Runtime\Triggers\ObservableTriggerExtensions.Component.cs(449,23): error CS0246: The type or namespace name 'Observable<>' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.cysharp.r3@4184a1734e\Runtime\UnityTimeProvider.cs(94,40): error CS0246: The type or namespace name 'ITimer' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.cysharp.r3@4184a1734e\Runtime\Triggers\ObservableAnimatorTrigger.cs(22,17): error CS0246: The type or namespace name 'Unit' could not be found (are you missing a using directive or an assembly reference?)
```

I know these errors are normally solved adding the assembly definition as a reference, but I've already done that. Is there anything special about the way R3 is packaged that requires some different setup? Thank you!

**Comment by neuecc** [comment]
You need to install R3 core library from NuGet before use Git URL.
https://github.com/Cysharp/R3?tab=readme-ov-file#unity
