### ISSUE TITLE
Blazor Support

### ISSUE THREAD

**Issue by michaelstonis** [Cysharp/R3#139]
Is Blazor Support possible?

What could a `TimeProvider` look like? There is no direct dispatcher and the `StateHasChanged` method is not very granular. I could still see there being a benefit in having something to automatically call `StateHasChanged` based on property updates or similar though.

**Comment by neuecc** [comment]
I see, Blazor also seems to have a SynchronizationContext, so it may be possible to do something.

**Comment by neuecc** [comment]
I've implemented SynchronizationContextTimeProvider for Blazor.
StateHasChanged should be executed manually.

![image](https://github.com/Cysharp/R3/assets/46207/055b0469-df52-4c5b-9da1-d358babf9e07)

**Comment by neuecc** [comment]
I've introduced `AddBlazorR3` for default TimeProvider as request scoped.
https://github.com/Cysharp/R3?tab=readme-ov-file#blazor

**Comment by michaelstonis** [comment]
> I've implemented SynchronizationContextTimeProvider for Blazor. StateHasChanged should be executed manually.
> 

I think this is great! Having `StateHasChanged` called manually seems like a reasonable expectation since we don't have a better way to manage it and it would be better to be careful with how many updates we push there.
