### ISSUE TITLE
SystemRuntime.CompilerServices.Unsafe missing

### ISSUE THREAD

**Issue by tattyd** [Cysharp/R3#142]
Hello again,

Steps:

1. Installed R3 via NuGet for Unity
2. Installed R3 via Unity Package manager and Git URL
3. Errors in console:

```
Assembly 'Assets/Packages/R3.1.0.4/lib/netstandard2.0/R3.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Runtime.CompilerServices.Unsafe'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
```

From some research it looks like you may have had similar issues in the past (https://github.com/MessagePack-CSharp/MessagePack-CSharp/issues/716) , so I'm filing an issue to see if you have any specific advice.

When installing from NuGetForUnity, I see this message from NuGetForUnity in the Console:

```Package System.Runtime.CompilerServices.Unsafe.6.0.0 is already imported in engine, skipping install.```

Which implies NuGet thinks the correct version (6.0.0) is already available - but the Unity engine disagrees.

Thank you,
David

**Comment by neuecc** [comment]
Are you installing other packages? If so, please list the names of those packages.

**Comment by tattyd** [comment]
Hello!

From Unity Package manager:
- A* Pathfinding Project - 4.3.65
- R3 -1.0.4
- UniTask - 2.3.3
- LinqGen - 0.2.2
- Heap Explorer - 4.1.1

From Unity:
- AI Navigation
- Burst
- Cinemachine
- Collections
- Custom NUnit
- Editor Coroutines
- Entities
- Jetbrains Rider
- Jobs
- Mathematics
- Memory Profiler
- Mono Cecil
- Newtonsoft
- Performance testing
- Post Processing
- Scriptable Build Pipeline
- Serialization
- Test Framework
- Timeline
- Profiling Core API
- Unity UI
- Version Control

From NuGet for Unity:
- MS.Bcl.Asyncinterfaces
- MS.Bcl.TimeProvider
- ObservableCollections
- R3
- System.Threading.Channels

**Comment by neuecc** [comment]
If no packages have been installed, there probably won't be any issues.
Could you investigate which package is causing the conflict?
That way, we might be able to think of a solution.

**Comment by tattyd** [comment]
I can try - do you have any advice on how to do that, apart from removing all packages and adding one by one?

**Comment by neuecc** [comment]
I don't know, do removing all packages and adding one by one.

**Comment by SlaggyWolfie** [comment]
Might require a new issue from me, but "System.Runtime.CompilerServices.Unsafe" is included in the UPM "Collections" package. v2.6.8 of Collections removes that aforementioned library, which prevents building via a linker error such as:
```
C:\Program Files\Unity\Hub\Editor\6000.0.73f1\Editor\Data\il2cpp\build\deploy\UnityLinker.exe @Library\Bee\artifacts\rsp\3550708449680981278.rsp
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: System.Runtime.InteropServices.CollectionsMarshal.AsSpan<T>(List<T>): Error processing method 'System.Runtime.InteropServices.CollectionsMarshal.AsSpan<T>(List<T>)' in assembly 'R3.dll'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Unity.IL2CPP.Common.MissingMethodStubber.GetTypeModule(TypeReference type, IEnumerable`1 assemblies)
   at Unity.Linker.Steps.AddUnresolvedStubsStep.MarkAssemblyOfType(UnityLinkContext context, TypeReference type)
   at Unity.Linker.Steps.Marking.UnresolvedStubMarking.HandleUnresolvedType(TypeReference reference)
   at Unity.Linker.Steps.Marking.UnresolvedStubMarking.HandleUnresolvedMethod(MethodReference reference)
   at Unity.Linker.Steps.UnityMarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction, MethodDefinition method, Boolean& requiresReflectionMethodBodyScanner)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
```

The removal is visible at: https://docs.unity3d.com/Packages/com.unity.collections@2.6/changelog/CHANGELOG.html#268---2026-07-10

Collections v2.6.7 retains the library and allows building. 

There might be other solutions but this was simplest.
