### ISSUE TITLE
validator of BindableReactiveProperty

### ISSUE THREAD

**Issue by maonaoda** [Cysharp/R3#152]
すみません、既存のエラーの削除がここで行われていませんか?
https://github.com/Cysharp/R3/blob/62efb115f182616f49aba7f71340779b97178707/src/R3/BindableReactiveProperty.cs#L97-L104

**Comment by neuecc** [comment]
おお！
Clearを忘れている、Clearが必要である、という意味で良いですか？（そうだと思います……！）

**Comment by maonaoda** [comment]
そうだと思います、validatorでの検証ですが、値が正しくても、前回発生したエラーがいつあります。

**Comment by neuecc** [comment]
急ぎ修正します、ありがとうございます！

**Comment by neuecc** [comment]
I've released `v1.1.2`, it includes fix for this.
