### ISSUE TITLE
Join Dotnet Foundation

### ISSUE THREAD

**Issue by eder-em** [Cysharp/R3#160]
Is it possible to add this project to the dotnet foundation? The company I work for has a huge resitence to use OSS libraries that are not part of DNF? Could you please consider that, I think it would help developers like me to adopt it on corporate applications.

**Comment by michaelstonis** [comment]
I wouldn't recommend it. The process is long and arduous. I am not sure that it ultimately provides a lot of benefits.

I would look at the track record and quality of the libraries offered by Cysharp as more of a reason to use them than being part of the DNF. If being part of the DNF is a blocker for your company, then I think you will be facing a tremendous uphill battle for with library use.

**Comment by neuecc** [comment]
I have no intention of joining the .NET Foundation.
Recently, Avalonia decided to leave the foundation.
https://github.com/AvaloniaUI/Avalonia/discussions/14666

Currently, the .NET Foundation is largely dysfunctional and there are no particular benefits for us.
I hope you company will reconsider their selection criteria.

**Comment by eder-em** [comment]
Thank you for anwering @neuecc . And congrats for the amazing job on ReactiveProperty and now R3
