### ISSUE TITLE
ReactiveProperty PropertyDrawer for Unity

### ISSUE THREAD

**Issue by neuecc** [Cysharp/R3#17]
needs SerializableReactiveProperty?

**Comment by KazukiKuriyama** [comment]
I do not use ReactiveProperty itself, and for similar purposes I use the following API, so I don't really see the need for it.

`ObserveEveryValueChanged(this T value) -> Observable.EveryValueChanged(T value)`

**Comment by neuecc** [comment]
The SerializableReactiveProperty has the advantage of being directly modifiable from the inspector.
Additionally, since EveryValueChanged is polling, it differs in its exact behavior, and from a performance standpoint, ReactiveProperty may often be more advantageous.
However, I am very pleased to see that EveryValueChanged is being effectively utilized.

**Comment by KazukiKuriyama** [comment]
When serializing EveryValueChanged, the target was given `[field: SerializeField]`.
So EveryValueChanged was polling! Thanks for letting me know!
