### ISSUE TITLE
Error when added to project

### ISSUE THREAD

**Issue by inexts1996** [Cysharp/R3#172]
Unity 2022.3.16f1
visual studio 2022
![image](https://github.com/Cysharp/R3/assets/43948140/2a50d2a6-01d5-42d6-8fd2-42110b46ecf1)

**Comment by inexts1996** [comment]
I deleted the library and then reloaded it and still got the error

**Comment by neuecc** [comment]
Add Core library from NuGet before add Unity Extensions.

**Comment by inexts1996** [comment]
Thank you, it has been resolved @neuecc
