### ISSUE TITLE
Problem with installing the latest R3 version in Unity

### ISSUE THREAD

**Issue by TonyZub** [Cysharp/R3#173]
Faced an issue, while trying to install R3 via git URL - there are some scripts that are written with C#10 syntax - and unity (even quite new version - 2021-2022) don't understand it (as a result - compilation errors). But when I tried NuGet - everythin went quite well, but (somehow) there were not all classes included in the latest version (at least SerializableReactiveProperty was missing). And to fix that I just added some classes directly from Zip to my project (after installation with NuGet) and everything seems fine, however it would be great if there were no need to do stuff like that and all you has to do was just installing the package from one source =)

P.S Maybe I just failed to read the ReadMe properly, or messed something up (didn't see any similar issues and thought to leave one here, in case I'm not alone)

**Comment by neuecc** [comment]
I'm not sure what issues you are encountering, but the installation requires two steps. Not just one, but both. First, install the core from NuGet, and then install the Unity extension with the git reference.

**Comment by TonyZub** [comment]
Yep, I'm just lack of attention while reading the instruction, my bad, thanks for help =)
