### ISSUE TITLE
r3 vs rx.net

### ISSUE THREAD

**Issue by man-chi** [Cysharp/R3#189]
My team is developing VR Unity, a Windows desktop app, and dotnet full-stack on Azure cloud.

we are impressed and appreciate the great work by R3 and uniRx community.

What are the key differences between R3 vs rx.net? kindly advise
https://github.com/dotnet/reactive

**Comment by neuecc** [comment]
As mentioned at the beginning of the ReadMe, the biggest difference is that it does not stop on error.
Also, the dotnet/reactive ecosystem is not applicable due to the different interface.
This may or may not be a good thing.

**Comment by man-chi** [comment]
@neuecc thanks for your great feedback.

quick question:
our team would like to do a book club for members who will be developing Rx based on R3. Would you recommend the "introduction-to-rx-dotnet" book to start with?
https://endjincdn.blob.core.windows.net/assets/ebooks/introduction-to-rx-dotnet/introduction-to-rx-dotnet-2nd-edition.pdf

**Comment by neuecc** [comment]
I think it is generally good.
Many of the concepts can be applied as they are.
In my personal opinion, there are a few points where some not-so-good examples are included, but it should not be a major problem.

**Comment by man-chi** [comment]
may I know whether R3 is built on top of rx. net, any relationship in term of code and dependency between these two frameworks?

**Comment by neuecc** [comment]
There are no dependencies or shared interfaces between R3 and dotnet/reactive.
The relationship is completely independent.
