### ISSUE TITLE
the best use case to integrate MessagePipe to R3?

### ISSUE THREAD

**Issue by man-chi** [Cysharp/R3#194]
I have found another great open-source project called messagepipe, https://github.com/Cysharp/MessagePipe.

What is the best use case for both? in my current understanding:

MessagePipe is a simple point-to-point connection, both sync and async. best used for implementing the event handler to handle commands and queries, it could also act as a middle-layer integration to R3 for event processing.

R3 is an event bus, best used for pub/sub, one-to-many asynchronous connection, designed to do more advanced event processing in memory 

in general, messagepipe is a good starting point, then further integrated with R3. Is my understanding correct? please advise.

**Comment by neuecc** [comment]
DI-based lifetime management and reachability control including asynchronous operations (IAsyncPublisher/IAsyncSubscriber) cannot be achieved with Rx signatures.

Therefore, I believe they will continue to exist as separate projects.
