### ISSUE TITLE
[Questions] Interaction with DynamicData ?

### ISSUE THREAD

**Issue by reegeek** [Cysharp/R3#20]
Hi,

As always thank for sharing your incredible work.

I often use dotnet/reactive with [DynamicData](https://github.com/reactivemarbles/DynamicData) to build and bind collections in WPF.
As you have published [ObservableCollections](https://github.com/Cysharp/ObservableCollections), I suppose you have also this kind of needs.

Do you think we can imagine building (and binding) collections with R3 ?

regards.

**Comment by neuecc** [comment]
`IObservable<T>` can be converted to `Observable<T>` and used as is!
ObservableCollections will be changed to the R3 version when R3 is officially released.

**Comment by jcummings2** [comment]
See https://github.com/michaelstonis/R3Ext
