### ISSUE TITLE
The type or namespace name 'Collections' does not exist in the namespace 'R3' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by dyguests** [Cysharp/R3#205]
Unity 2022.3.15f1

Platform: WebGL

I try to `Install the R3.Unity package by referencing the git URL`

```
"com.cysharp.r3": "https://github.com/Cysharp/R3.git?path=src/R3.Unity/Assets/R3.Unity#1.1.11",
```

Then it happened:

```
Library\PackageCache\com.cysharp.r3@96c13c71cb\Runtime\UnityFrameProvider.cs(1,10): error CS0234: The type or namespace name 'Collections' does not exist in the namespace 'R3' (are you missing an assembly reference?)
```

![image](https://github.com/Cysharp/R3/assets/7933189/92551628-a641-44a0-8665-8c93acaa0288)

Did I missing something?

**Comment by dyguests** [comment]
It works by `Install R3 from NuGet using [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity)`
not works by `Install the R3.Unity package by referencing the git URL`

fixed.

**Comment by namquang93** [comment]
It's weird that installing only works in 1 way.

**Comment by johanhelsing-attensi** [comment]
Just ran into this, I don't think it should be closed if it still happens with a documented installation method.

EDIT: ehm, in my case it might have just been that I forgot to commit `packages.config` 🤦
