### ISSUE TITLE
SubscribeOnMainThread usage in Unity

### ISSUE THREAD

**Issue by zhang-z** [Cysharp/R3#209]
I'm new to R3/Rx.NET. Thinking of refactoring my Unity game in this design pattern:
- Have a big global DataStore class, containing all data & settings used in the game.
- The data could be modified in multi-threads: user input events; a dedicate battle engine thread; web request thread, etc.
- Some MonoBehavior classes use `SubscribeOnMainThread` method to respond to certain data change events and modify the Unity game objects.

Is `Subscribe**OnMainThread**` necessary? Am I using R3 in the correct way? Thanks.

Another question for `SubscribeOnMainThread`, what if an Observable event happens twice between two frames. What is gonna happen in the MainThread? Handler code executed twice in sequence?

**Comment by TORISOUP** [comment]
The `SubscribeOnMainThread` is an operator that adjusts when to subscribe to the `Observable` (register the Observer to the Observable).

Therefore, once the subscribe process is complete and the message is ready to be received, the operator has no further significance, and the operator does not perform any operation in the order in which the messages are issued.
