### ISSUE TITLE
Unity il2cpp performance is lower than mono

### ISSUE THREAD

**Issue by jsaon-L** [Cysharp/R3#220]
In my opinion, il2cpp should run faster than momo
but
I tested the performance of Subject and found that the performance of il2cpp is lower than that of mono.

build il2cpp execution time `1811` milliseconds
build mono execution time `485` milliseconds

I do not know why
my test code
```
    int i;
    void Start()
    {
        btn.onClick.AddListener(() => {
            var sw = Stopwatch.StartNew();
            TestR3Subject();
            sw.Stop();
            textMeshPro.text = "use time:" + sw.ElapsedMilliseconds;
        });

    }

    public void TestR3Subject()
    {
        Subject<EventBusMsg<int>> subject = new Subject<EventBusMsg<int>>();
        var msg = new EventBusMsg<int>() { Value = 1 };
        for (int i = 0; i < 1000; i++)
        {
            subject.Subscribe(OnReceiveMsg);
        }

        for (int i = 0; i < 100000; i++)
        {
            subject.OnNext(msg);
        }
    }

    public void OnReceiveMsg(EventBusMsg<int> msg)
    {
        i++;
    }

```

Unity 6000.0.0f1
Windows Build
PlayerSetting
![image](https://github.com/Cysharp/R3/assets/17309378/7ce1e829-deca-4986-ab93-e5a671710963)
R3.1.1.12
![image](https://github.com/Cysharp/R3/assets/17309378/5dcdca96-dde7-4bde-8100-c024eb30e65d)

**Comment by jsaon-L** [comment]
I tested UniRX with the same code
UniRX has the same performance of `300` milliseconds in mono and il2cpp

**Comment by neuecc** [comment]
Thanks, that's interesting and I'll investigate.

**Comment by neuecc** [comment]
From my research, the synchronization primitives (volatile, lock, interlocked) in IL2CPP seem to be slower than mono.
R3 uses Volatile more than UniRx, so it seems to have more impact.
For critical paths, I will remove the volatile and bring the performance back to the same level as before.
I will also report this to Unity.

Code and IL2CPP Build result:
![image](https://github.com/user-attachments/assets/2868883a-5724-40b0-8f3f-52f58dbed7d8)

Mono Build result:
![image](https://github.com/user-attachments/assets/47b52ec2-73f5-4a42-8a49-2ed21524edc4)

**Comment by neuecc** [comment]
v1.2.0 reduces use of volatile and changes Subject implementation.
