### ISSUE TITLE
Install R3 with git url causes compile errors

### ISSUE THREAD

**Issue by BrettHuang2019** [Cysharp/R3#221]
Unity 2021.3.11f1
R3 1.1.12
Is it missing some dependencies? 

![image](https://github.com/Cysharp/R3/assets/54031246/a48f1324-99b8-4d63-94c3-9d5f40bec48e)

**Comment by jsaon-L** [comment]
You need to install NuGet and then install R3
https://github.com/Cysharp/R3?tab=readme-ov-file#unity
