### ISSUE TITLE
Seemingly unavoidable "System.InvalidOperationException: Disposable is already assigned." in certain case

### ISSUE THREAD

**Issue by Ifhay** [Cysharp/R3#226]
I've encountered this exception when trying to create a nested Observable chain.
<img width="408" alt="disposable" src="https://github.com/Cysharp/R3/assets/18574763/5433c84b-e785-4944-bc66-f00c2aec3866">
<img width="401" alt="console" src="https://github.com/Cysharp/R3/assets/18574763/87404dc6-a374-4989-b6ce-cc3c4dbce5a9">

As far as I understand, if the Observable that is returned from inside `Defer` has `SubscribeOn...` operator, then the outer SubscribeOn results in an error.

Is this intended?

Thanks!

**Comment by neuecc** [comment]
When treating a `List<T>` as an `IEnumerable<T>`, there should be performance differences. Are you considering such factors?"

**Comment by Ifhay** [comment]
> When treating a `List<T>` as an `IEnumerable<T>`, there should be performance differences. Are you considering such factors?"

I don't think I understand, sorry.
Could you elaborate, please?

**Comment by neuecc** [comment]
Oh, I'm sorry! It seems I was replying to the wrong part! This is a reply to another Issue.

**Comment by neuecc** [comment]
And thank you, this seems `Defer` s bug.
I'll fix and release soon(maybe today).

**Comment by neuecc** [comment]
fixed on 1.1.13.
