### ISSUE TITLE
`ReplaySubject` race condition

### ISSUE THREAD

**Issue by nepolak** [Cysharp/R3#228]
I've spotted a bug with ReplaySubject, which may leave newly-subscribed observer without some new notifications in rare cases in a current version (v. 1.1.12) 

When an observer subscribes to `ReplaySubject`, it receives stored notifications [under a lock](https://github.com/Cysharp/R3/blob/d0ee86f6bb8b7e2809f1dd317c62d5d610356c92/src/R3/ReplaySubject.cs#L94), but then it is registered to ReplaySubject [without the lock](https://github.com/Cysharp/R3/blob/d0ee86f6bb8b7e2809f1dd317c62d5d610356c92/src/R3/ReplaySubject.cs#L115). If in between these lines, [OnNext](https://github.com/Cysharp/R3/blob/d0ee86f6bb8b7e2809f1dd317c62d5d610356c92/src/R3/ReplaySubject.cs#L51) is called with a new notification from another thread, the observer will miss the new notification because its emission [is not synchronized](https://github.com/Cysharp/R3/blob/d0ee86f6bb8b7e2809f1dd317c62d5d610356c92/src/R3/ReplaySubject.cs#L61) with new subscriptions.

dotnet/reactive implements `ReactiveSubject` with synchronization of both notification [emission](https://github.com/dotnet/reactive/blob/4f341fc2d50d86aa13e8f46e8e44904f3716dfca/Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs#L251) and [subscription](https://github.com/dotnet/reactive/blob/4f341fc2d50d86aa13e8f46e8e44904f3716dfca/Rx.NET/Source/src/System.Reactive/Subjects/ReplaySubject.cs#L350).

Easy way to fix that is to put subscription (SubscribeCore) and notification emission (OnNext) under the lock too.

**Comment by neuecc** [comment]
Thanks for the details, this issue is important and I will check it out right away.

**Comment by ninjaoxygen** [comment]
Just to confirm we are also seeing what sounds like the same bug. It looks like a really short window of race only on the first OnNext/Value call. We have a test case with just ReactiveProperty -> Select -> Switch. In production we only see the bug around 1 in 200.

In our case, the Select constructs a new ReactiveProperty, subscribes over the network and calls OnNext within ~2ms. If we add a 10ms delay before the OnNext, it solves the problem, but then we need to add more locks to avoid out-of-order delivery.

If we swap the Select for SelectAwait before the Switch the bug goes away.

**Comment by nepolak** [comment]
> Just to confirm we are also seeing what sounds like the same bug. It looks like a really short window of race only on the first OnNext/Value call. We have a test case with just ReactiveProperty -> Select -> Switch. In production we only see the bug around 1 in 200.
> 
> In our case, the Select constructs a new ReactiveProperty, subscribes over the network and calls OnNext within ~2ms. If we add a 10ms delay before the OnNext, it solves the problem, but then we need to add more locks to avoid out-of-order delivery.
> 
> If we swap the Select for SelectAwait before the Switch the bug goes away.

Seems like race condition also, because OnNext is not synchronized with subscriptions. Current value of ReactiveProperty is emitted to a new observer [without a lock](https://github.com/Cysharp/R3/blob/6b73e401d62b5581a088a7c3a4da4f60586ae4fa/src/R3/ReactiveProperty.cs#L213), and only subscription is under the lock. It is possible to call OnNext, which [doesn't seem to have any synchronization at all](https://github.com/Cysharp/R3/blob/6b73e401d62b5581a088a7c3a4da4f60586ae4fa/src/R3/ReactiveProperty.cs#L131), in between these lines and have a notification missing.

**Comment by nepolak** [comment]
> > If we swap the Select for SelectAwait before the Switch the bug goes away.
> 
> I'd rather reimplement ReactiveProperty with locking in OnNext and SubscribeCore and see if it goes away. I think the problem is in ReactiveProperty and not in Select/SelectAwait or Switch.

Just investigated `Switch`, it seems fine, I don't see any possibility for race condition there.

**Comment by nepolak** [comment]
> Thank you, once we release the current fix code that includes the ReplaySubject issue, we will look into this issue as soon as possible.

I've created a [pull request](https://github.com/Cysharp/R3/pull/230) for the ReactiveProperty issue
