### ISSUE TITLE
[Unity 6] Can not Handle Error When Using [Observablelist].ObserveAdd().Subscribe(function)

### ISSUE THREAD

**Issue by franktmy** [Cysharp/R3#236]
When work with ObservableCollections.R3 in Unity 6. 

Code is:

Observablelist.ObserveAdd()
    .Subscribe(x =>
    {
        throw new SystemException("log error test");
    });

There isn't any error log on the unity console,So how can I handle error in this case?

**Comment by franktmy** [comment]
Fixed:There isn't any error log on unity console when I add element to the list .

**Comment by neuecc** [comment]
I can't reproduce it.

![image](https://github.com/user-attachments/assets/7ed1ed2e-e33a-4b83-9ad3-2f12d9ae8821)

```csharp
using ObservableCollections;
using R3;
using System;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    ObservableList<int> Observablelist = new ObservableList<int>();

    void Start()
    {
        Observablelist.ObserveAdd()
            .Subscribe(x =>
            {
                throw new SystemException("log error test");
            });

        Observablelist.Add(1);
    }
}
```

**Comment by franktmy** [comment]
> I can't reproduce it.
> 
> ![image](https://private-user-images.githubusercontent.com/46207/351153518-7ed1ed2e-e33a-4b83-9ad3-2f12d9ae8821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTc4MTAsIm5iZiI6MTcyMTY5NzUxMCwicGF0aCI6Ii80NjIwNy8zNTExNTM1MTgtN2VkMWVkMmUtZTMzYS00YjgzLTlhZDMtMmYxMmQ5YWU4ODIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAxMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNGM3YWRlMTQwYWRlMGEyZDMyNjUwOTI2NWM3N2UwMTA1ZGQ5NDk1NWI4N2Q5ZDUxZWFlMmQ0NzUwZmU3M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.se36lAZaKnHRyeXwswjLi3kceEYbyHgCOtSb1Vm921g)
> 
> ```cs
> using ObservableCollections;
> using R3;
> using System;
> using UnityEngine;
> 
> public class NewBehaviourScript : MonoBehaviour
> {
>     ObservableList<int> Observablelist = new ObservableList<int>();
> 
>     void Start()
>     {
>         Observablelist.ObserveAdd()
>             .Subscribe(x =>
>             {
>                 throw new SystemException("log error test");
>             });
> 
>         Observablelist.Add(1);
>     }
> }
> ```
I‘m sorry I don’t mention the actually vision,I'm in 6000.0.5f1
https://unity.com/cn/releases/editor/whats-new/6000.0.5
```
using ObservableCollections;
using R3;
using System;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    ObservableList<int> Observablelist = new ObservableList<int>();

    void Start()
    {
        Debug.Log("I'm Start!");
        Observablelist.ObserveAdd()
            .Subscribe(x =>
            {
                throw new SystemException("log error test");
            });

        Observablelist.Add(1);
        Debug.Log("I'm End!");
    }
}
```
![屏幕截图 2024-07-23 092651](https://github.com/user-attachments/assets/2f803701-b040-4cbc-b058-460c6916a188)

![屏幕截图 2024-07-23 092332](https://github.com/user-attachments/assets/4a23c99a-1577-4f99-9e0e-23f44f10087e)

**Comment by neuecc** [comment]
The latest seems to be 6000.0.11f1, so could you try 6000.0.11f1?
Also, did you include R3 from PackageManager with the additional steps?
If you don't include it, the unhandled exception will not be notified to the Unity Console.

**Comment by franktmy** [comment]
You are right,the reason is I missed step 2: Install the R3.Unity package by referencing the git URL.
Thank you for your patience.
