### ISSUE TITLE
Strange SelectAwait behaviour

### ISSUE THREAD

**Issue by kamend** [Cysharp/R3#237]
I have this code, where I would expect that SelectAwait will complete like normal and return "result", but for some reason, because I have put Take(1), before SelectAwait, the chain will be disposed and the CancellationToken in SelectAwait will get canceled.

If I make the chain like this: str.SelectAwait(async (v, ct) => await Something(ct)).Take(1), it works fine. 

But I really dont understand why the first option does not work, am I understanding this wrong or? 

The main usecase I have is that str is some state, but I just want to take the current value of and use it in the async action in SelectAwait, but without Take(1) it will cause multiple runs of the async action, if the state is updated while it is running.

```csharp
async ValueTask<string> Something(CancellationToken ct) {
    Console.WriteLine("Starting Task");
    await Task.Delay(3000, ct);

    return "result";
}


ReactiveProperty<string> str = new ReactiveProperty<string>("test");
Subject<int> v = new Subject<int>();

var d = v.SelectMany(v => Observable.Concat(
    str.Take(1).SelectAwait(async (v, ct) => await Something(ct))
)).Subscribe(v => {
    Console.WriteLine(v);
});

v.OnNext(0);
```

**Comment by kamend** [comment]
Here is one more simple example where we can clearly see that the CancellationToken gets canceled for some reason:
```
async ValueTask<string> Something(CancellationToken ct) {
    Console.WriteLine("Starting Task");
    await Task.Delay(1000);
    Console.WriteLine("Ending Task");
    Console.WriteLine(ct.IsCancellationRequested);
    return "result";
}

Subject<int> v = new Subject<int>();

var dd = v
.Take(1)
.SelectAwait(async (v, ct) => await Something(ct))
.Subscribe(v => {
    Console.WriteLine(v);
});

v.OnNext(0);
```
The result here is: 
```
Starting Task
Ending Task
True
```

If I add the CancellationToken to Task.Delay(), we will never see "Ending Task".

**Comment by neuecc** [comment]
Take(1) provides OnCompleted during Task.Delay.
Therefore, it is not surprising that it is cancelled.

**Comment by kamend** [comment]
I would expect that I can take the first value of something and then do an async action afterwards. The current behaviour seems a bit unexpected, if you look at the code of the defined chain, but it might be just me.

How would I do this logic differently than something it like this: 
```
var dd = v
.SelectAwait(async (v, ct) => await Something(ct), AwaitOperation.Drop)
.Take(1)
.Subscribe(v => {
    Console.WriteLine(v);
});
```

**Comment by kamend** [comment]
Playing around with this more, I guess using the AwaitOperation.Sequential(which is the default one) will do the job in case of Take(N) results.  I dont know why I have the wrong notion that placing Take before the async action make more sense in terms of being correct declaratively. Because in the first case I read it like this: "Take the first value of something and run this action" in the second case it reads something like: "Run this action for every value of N, but return only the first result", of course it will run the action only one time because of the Sequential option.

```
var dd = v
.SelectAwait(async (v, ct) => await Something(ct))
.Take(1)
.Subscribe(v => {
    Console.WriteLine(v);
});
```

**Comment by neuecc** [comment]
Thanks.
Now it is being processed from both the upstream OnCompleted and downstream Dispose as a trigger for CancellationToken.
If I were to change the behavior, I would make CancellationToken trigger only Dispose, and OnCompleted wait until all queues have been processed before publishing.
Delay behaves similarly, and in a sense, so does the internal Channel itself.
It is definitely more natural that way, so I will consider changing it.
It would be a breaking change, but it would be ok.

**Comment by neuecc** [comment]
I had completely forgotten, but it was already possible to control it with the bool cancelOnCompleted option.
However, the default for this is true, but I think false would be preferable.
I'm going to change it to false in the next release, when I increase the minor version.

**Comment by kamend** [comment]
> I had completely forgotten, but it was already possible to control it with the bool cancelOnCompleted option. However, the default for this is true, but I think false would be preferable. I'm going to change it to false in the next release, when I increase the minor version.

Thank you! And thank you for the prompt response and the awesome library!

**Comment by neuecc** [comment]
v1.2.0 changes default behavior.
