### ISSUE TITLE
TakeUntil with a predicate?

### ISSUE THREAD

**Issue by OpenEnergyGroup** [Cysharp/R3#238]
Consider a sequence of booleans e.g. `[false, false, false, true]` - the ideas is to keep iterating until True. Initially I thought you could `TakeWhile(b => false)` and then have a separate action on Completion. This works, but only if we *start* with false. If the sequence is `[true, false, ... ]` then that strategy won't work, because TakeWhile will never happen.

(I believe this has been implemented in RxJava as `TakeWhile `with an optional emit-last-value parameter.) 

It's quite useful I believe, and not achievable easily with the existing patterns.

Thank you.

**Comment by 1619digital** [comment]
Hi, yes `TakeWhile(predicate, bool emitLastValue)` is functionally equivalent to `TakeUntil(inverse-predicate)`

This in RxJS:
``
```
import { from, takeWhile } from 'rxjs';

var sequence = ["A", "B", "C", "D", "E", "F", "G"]

from(sequence).pipe(takeWhile(x => x !== "E", true)).subscribe(x => console.log(x)); // => ABCDE

from(sequence).pipe(takeWhile(x => x !== "A", true)).subscribe(x => console.log(x)); // => A
```

However, I suggest `TakeUntil(predicate)` is more understandable, and isn't hiding behind a magic flag. Also, you already have TakeUntil, and Rx.NET [has it in this form too](https://github.com/dotnet/reactive/blob/main/Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntilPredicate.cs). 

So in the above, much more intuitive to say `TakeUntil(x => x == "E")` or `TakeUntil(x => x == "A")`

Thanks.

**Comment by neuecc** [comment]
v1.2.0 added `TakeUntil(predicate)`, thanks.
