### ISSUE TITLE
[Suggestion] Break README.md down to a Wiki

### ISSUE THREAD

**Issue by galvesribeiro** [Cysharp/R3#241]
@neuecc as always THANK YOU! Freaking amazing!

As a suggestion, how do you feel about breaking the `README.md` into a Wiki on Github with multiple topics?

It is pretty hard to navigate and follow that huge page and I think it would be nice if we had Wiki pages per topic instead.

Again, thank you for more one awesome library!

**Comment by neuecc** [comment]
I don't like GItHub Wiki.
Please use table of contents.
![image](https://github.com/user-attachments/assets/d9342cb1-5679-4555-97f5-28143848a1a0)
