### ISSUE TITLE
Subject etc. should implement virtual Dispose pattern 

### ISSUE THREAD

**Issue by OpenEnergyGroup** [Cysharp/R3#253]
Hi, the Dispose pattern of `Subject` does not implement 

```
protected virtual void Dispose(bool disposing){
...
}
```

it's instead 

```
   public void Dispose(bool callOnCompleted)

```

which makes it impossible to inherit from Subject with a class that needs to call its own Dispose before the base. The canonical Microsoft solution examples are [here ](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose ).

Thank you!

**Comment by neuecc** [comment]
Subject is not designed to be inherited, if it is misleading as such, it should be sealed.
