### ISSUE TITLE
Updating ReactiveProperty bound with x:Bind from non-UI thread in WinUI 3 causes System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by southernwind** [Cysharp/R3#254]
I am encountering an issue in a WinUI 3 application where updating a ReactiveProperty that is bound to the UI using x:Bind from a non-UI thread results in a System.Runtime.InteropServices.COMException.

**Steps to Reproduce:**
1.	Create a ReactiveProperty in a ViewModel.
2.	Bind the ReactiveProperty to a UI element using x:Bind.
3.	Update the ReactiveProperty from a non-UI thread (e.g., using Task.Run).

**Example Code:**
```C#
public class ReactivePropertyViewModel {
    public ReactiveProperty<int> Count { get; } = new();

    public ReactiveCommand IncrementInTaskCommand { get; } = new();

    public ReactivePropertyViewModel()
    {
        this.IncrementInTaskCommand.Subscribe(() => {
            Task.Run(() =>
            {
                this.Count.Value++;
            });
        });
    }
}
```

**Expected Behavior:**
The ReactiveProperty should be updated without causing any exceptions.

**Actual Behavior:**
A System.Runtime.InteropServices.COMException is thrown when the ReactiveProperty is updated from a non-UI thread.

Any guidance on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by southernwind** [comment]
You can find a minimal reproducible example in the following repository: https://github.com/southernwind/R3WinUITest

**Comment by neuecc** [comment]
ReactiveProperty does not automatically assignment to UI Threads, so you must control it yourself.
The most commonly used is `ObserveOn`,
For example
```csharp
IncrementInTaskCommand./* Operators */.ObserveOnCurrentSynchronizationContext().Subscribe(x => { } )
```
would be written like this, and the inside of the Subscribe would be processed on the UI thread.

**Comment by southernwind** [comment]
Thank you. This issue has been resolved.
