### ISSUE TITLE
Request for Non-Generic ReactiveCommand in R3 Library

### ISSUE THREAD

**Issue by southernwind** [Cysharp/R3#255]
I am currently using the R3 library and have noticed that only generic versions of `ReactiveCommand` are available (`ReactiveCommand<T>`). It would be very helpful to have a non-generic version of `ReactiveCommand` as well.

**Current Situation:**
•	Only `ReactiveCommand<T>` is available.
•	Every time I need to use a command without a specific type, I have to write `ReactiveCommand<Unit>`, which is inconvenient.

**Requested Feature:**
•	Introduce a non-generic `ReactiveCommand` in addition to the existing `ReactiveCommand<T>`.
•	Allow the following syntax: `public ReactiveCommand Command { get; }`.

**Benefits:**
•	Simplifies the code when no command parameter is needed.

It would be greatly appreciated if the library could be updated to include this feature. Thank you!

**Comment by neuecc** [comment]
good suggestion, I'll implement it.

**Comment by neuecc** [comment]
1.2.9 implemented it.
