### ISSUE TITLE
Unity 6 installation issue

### ISSUE THREAD

**Issue by bugfinders** [Cysharp/R3#258]
Packagemanager reports on installing the git url https://github.com/Cysharp/R3.git?path=src/R3.Unity/Assets/R3.Unity

I have other git urls installed (namely the base R3, nuget for unity etc)

[Package Manager Window] Error adding package: https://github.com/Cysharp/R3.git?path=src/R3.Unity/Assets/R3.Unity.
Unable to add package [https://github.com/Cysharp/R3.git?path=src/R3.Unity/Assets/R3.Unity]:
  Error while cloning package from Git repository (repository: https://github.com/Cysharp/R3.git, revision: 'HEAD', package path: root):
    Repository does not contain a package manifest:
      The file [C:\Users\me\Documents\Unity\17TEST\Library\PackageCache\.tmp-2628-h85ZJfermMVA\clone\package.json] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by neuecc** [comment]
I've tested latest Unity 6(`6000.0.20f1`) on Windows 11 but can not reproduce it.
