### ISSUE TITLE
Surprising difference of completion behavior between Subject.Dispose() and Observer.Dispose()

### ISSUE THREAD

**Issue by aliaumem** [Cysharp/R3#274]
Hi, I've recently stumbled upon some behavior that I found surprising regarding the disposal of subscriptions.

I used UniRx in the past, and I know the way `OnCompleted` works has changed, and I re-read the doc several times to make sense of it.
However, I still hit a case that feels wrong, and I'm not sure whether it is an intentional behavior change, or simply an oversight.

When disposing of the source observable, it makes sense that the subscriptions would get completed:
```csharp
Subject<Unit> subject = new();
subject.Subscribe(_ => {}, _ => Debug.Log("OnCompleted"));
subject.Dispose(); // prints "OnCompleted"
```
When an operator completes in the chain, the same thing happens. All good so far.
```csharp
Subject<Unit> subject = new();
subject.Take(1).Subscribe(_ => {}, _ => Debug.Log("OnCompleted"));
subject.OnNext(Unit.Default); // prints "OnCompleted"
```
However, if I manually dispose of the _observer_, the `onCompleted` callback never gets called
```csharp
Subject<Unit> subject = new();
var d = subject.Subscribe(_ => {}, _ => Debug.Log("OnCompleted"));
d.Dispose(); // nothing happens!!!
```

Is this the intended behavior? If it is, shouldn't the documentation explicitly say so?

**Comment by AnnulusGames** [comment]
This is correct behavior. Calling `Dispose()` on a subscription simply unsubscribes and has no effect on the completion of the observable. This is the same as in the original Rx.
