### ISSUE TITLE
Time/FrameProviders for platforms

### ISSUE THREAD

**Issue by neuecc** [Cysharp/R3#3]
- [x] WinForms
- [x] WPF
- [x] Avalonia
- [x] LogicLooper https://github.com/Cysharp/LogicLooper
- [x] MAUI
- [x] WinUI3
- [x] MonoGame
- [x] Unity
- [x] Godot
- [x] Stride

**Comment by alexei-lazari** [comment]
what about MAUI, Blazor ?

**Comment by neuecc** [comment]
MAUI is planning.
Maybe Blazor has no specific timer and message-loop so no needed.

**Comment by sgf** [comment]
If there is no need to interact with the ui, can winform be used directly. I use Core directly and it prompts me that I don't have a Frame Provider.

**Comment by neuecc** [comment]
We're just added WinForms FrameProvider.
In next release it include.
https://github.com/Cysharp/R3/tree/main/src/R3.WinForms

**Comment by sgf** [comment]
thanks for add winforms support

**Comment by sgf** [comment]
R3.Winforms not avaliable yet

> https://www.nuget.org/packages/R3.WinForms
> Error 404 - Page Not Found

**Comment by neuecc** [comment]
Yes, there is currently a problem with the NuGet server, and not all sub-packages have been uploaded.  
I have been inquiring to admin about this for a few days and am waiting for a response.

**Comment by neuecc** [comment]
@sgf now uploaded as `R3Extensions.WinForms` .

**Comment by sgf** [comment]
> @sgf now uploaded as `R3Extensions.WinForms` .

thanks
