### ISSUE TITLE
ReactiveCollection

### ISSUE THREAD

**Issue by Benna96** [Cysharp/R3#63]
UniRx had a class called ReactiveCollection. Does or will R3 have this as well?

**Comment by neuecc** [comment]
We have another library ObservableCollections.
https://github.com/Cysharp/ObservableCollections

I will make these ObservableCollections compatible with R3 before the official release, so that they can be used accordingly.

**Comment by neuecc** [comment]
I've released `ObservableCollections.R3` package.
