### ISSUE TITLE
Unity Triggers

### ISSUE THREAD

**Issue by neuecc** [Cysharp/R3#7]

**Comment by yenmoc** [comment]
I also think it is not necessary to be integrated into R3, R3 should only contain core features, although integrating it would be as a separate extension module like the case of UniRx. Personally, I find this useless. Overall, it still increases complexity

**Comment by tpnet** [comment]
Wish it was an expansion pack

**Comment by KazukiKuriyama** [comment]
Would it be useful to have it since it is used so often? I think it would be useful...

**Comment by neuecc** [comment]
Thank you for your feedback.
In R3, I would like to avoid having dynamic generation/addition of Components.

I want to make it easier for users to create their own Triggers as needed, either by providing an auxiliary base class for creating necessary Triggers or by offering sample code.

**Comment by neuecc** [comment]
v0.1.21 implemented triggers.
