### ISSUE TITLE
The option to limit maximum concurrency in AwaitOperation.*Parallel method

### ISSUE THREAD

**Issue by aneuf-tech** [Cysharp/R3#70]
I think `AwaitOperation` methods are a very powerful!

Now, any plans to add an option like `maxConcurrency` (or `maxDegreeOfParallelism`) to `AwaitOperation.*Parallel`?

It's common to want to control the maximum concurrent executions.

**Comment by aneuf-tech** [comment]
Thank you for considering!

**Comment by neuecc** [comment]
Ver.0.1.14 added it.

**Comment by Thaina** [comment]
This is amazing feature. Could we also have `AwaitOperation` and `maxConcurrent` for some other method like `ForEachAsync` ?
