### ISSUE TITLE
SerializableReactiveProperty serialized multiple times error

### ISSUE THREAD

**Issue by Ivan-Bastidas** [Cysharp/R3#75]
This started happening when I updated to the latest version today, my previous version was pulled on Jan 24, 2024, so the change that introduced the issue must have happened after that date

I have a SerializableReactiveProperty defined as 

`[SerializeField] private SerializableReactiveProperty<int> currentEnergy`

And every time it compiles it shows the following error in the console

![image](https://github.com/Cysharp/R3/assets/4523317/7e875bc3-07b4-4121-b0c1-7a851b880727)

My class inherits from `MonoBehaviour` and has no child classes

**Comment by Ivan-Bastidas** [comment]
@neuecc  I downloaded the latest version and I still get the same error

**Comment by neuecc** [comment]
This fix is inside in dll so could you try update NuGet dll and restart Unity?

**Comment by Ivan-Bastidas** [comment]
@neuecc you are right, its working now, thank you!
