### ISSUE TITLE
Delta time in R3.Godot

### ISSUE THREAD

**Issue by aneuf-tech** [Cysharp/R3#79]
In Godot, there is no direct equivalent to Unity's Time.deltaTime, and we use the `delta` parameter of the `_Process` or `_PhysicsProcess` method.

Currently, in R3, there is no straightforward way to access delta.

`GodotFrameProvider` and `FrameProviderDispatcher` store the value as `StrongBox<double>`, and I would appreciate it being exposed through some means.

**Comment by neuecc** [comment]
R3 uses TimeProvider.GetTimestamp to calculate time, should I calculate (add) this to the delta base?

**Comment by aneuf-tech** [comment]
Now that you mention it, it makes sense to use TimeProvider to calculate delta in this library that performs time abstraction.

However, I think that the raw value would be sufficient, for providing a way to easily use delta in Subscribe method or operator methods.

To be honest, I am not sure which approach is better for the library to provide.

**Comment by neuecc** [comment]
released.
