### ISSUE TITLE
Missing AsyncReactiveCommand<T>

### ISSUE THREAD

**Issue by RamiAhmed** [Cysharp/R3#86]
Hi, 

Thanks for the great library, been using it (in Unity) for a couple of weeks. 

I'm really missing an equivalent for [AsyncReactiveCommand<T>](https://github.com/neuecc/UniRx/blob/7cce378b3f8c8943b4cac8e847bdbb8e2e1802d1/Assets/Plugins/UniRx/Scripts/UnityEngineBridge/ReactiveCommand.cs#L137) which exists in UniRx, so I'm curious to hear whether there are plans to add it to R3, and if so if there's a timeline for it?

Thanks in advance.

**Comment by neuecc** [comment]
AwaitOperation.Drop for SelectAwait/WhereAwait/SubscribeAwait would be a close behavior.
Of course, they are not exactly the same.
First, please let me know if this satisfies your demand.

**Comment by RamiAhmed** [comment]
Thank you for the swift response!

I found SubscribeAwait, but without a way to execute the command asynchronously I don't really understand how it would achieve the same thing?

I have a flow like this:

AsyncCommand<object> OnExecute; // declared in a class
OnExecute.SubscribeAwait(DoWorkAsync).AddTo(this); // 'subscribers' providing the workload for the command (?)
OnExecute.Execute() // called e.g. from a GameManager, but I need this call to be async so that the rest of the scope waits 

I hope my explanation makes sense 🙏

**Comment by neuecc** [comment]
I'm not sure, what kind of code did you write in AsyncReactiveCommand?
