### ISSUE TITLE
Library Naming(R3 or UniRx or others)

### ISSUE THREAD

**Issue by neuecc** [Cysharp/R3#9]
should keep going UniRx(means Unified Rx), or use current R3, or others?
R3 means third-generation of Rx.

**Comment by tpnet** [comment]
I prefer R3 because it is concise and easy to understand.

**Comment by LuohuaRain** [comment]
What does 'R3' mean?

**Comment by vangogih** [comment]
R3 sounds like V8, sounds and looks amazing 🤟

**Comment by neuecc** [comment]
I am relieved to hear that the name R3 is more popular than I expected.
Rx3 seems a bit too blatant, so it's difficult to adopt.

**Comment by KazukiKuriyama** [comment]
I thought R3 had a cool name!

**Comment by stenyin** [comment]
may be "UR3"?

**Comment by LeoYang06** [comment]
R3 is neat and cool, but search engine unfriendly and unrecognizable.
Maybe a name with clear semantics would be better.
