### ISSUE TITLE
[Request] Alternative implementation of AsyncReactiveCommand

### ISSUE THREAD

**Issue by kochounoyume** [Cysharp/R3#97]
This may overlap with the story #86 , but I would like to do the simultaneous control of multiple UIs in R3, which was possible with the use of AsyncReactiveCommand in UniRx.

Drop for SelectAwait/WhereAwait/SubscribeAwait is basically a recognition that controls a single Observable, which is also useful, but falls one step short of the functionality we want.

AsyncReactiveCommand which exists in UniRx was implemented in the form of returning IObservable, but I personally hope that R3, which is highly compatible with async/await, will be implemented with a structure using async/await.

**Comment by neuecc** [comment]
Yes, we shouldn't just bring back the old one as is, at the very least, a different design is needed.
However, I have no ideas at the moment…….

**Comment by kochounoyume** [comment]
AsyncReactiveCommand was always used from the extension methods provided, but I think that was too uGUI-dependent an implementation.

R3, a general-purpose Rx, must create an API that can be used in situations where Unity is not available.

... This is very difficult.

Aside from being feasible, it might be useful if the following could be written : 

```cs
Button button;
ReactiveProperty<bool> gate;

void Start()
{
	button.OnClickAsObservable()
		.AsyncReactiveCommand(ref gate)
		.SubscribeAwait(async (_, ct) =>
		{
			var req = await UnityWebRequest.Get("https://google.com/").SendWebRequest().WithCancellation(ct);
			Debug.Log(req.downloadHandler.text);
		})
		.AddTo(this);
}
```

**Comment by neuecc** [comment]
I think it would be a combination of Drop and wrapping flag, like this

```
.SubscribeAwait( =>
   gate.Value = true;
   await CoreAsync();
    gate.Value = fasle;
);
```

When viewed like this, it doesn't seem significant enough to do as a standard.

**Comment by kochounoyume** [comment]
Indeed, it appears to be a simple implementation and meets the requirements.

If you don't want to write the same description every time, you can provide your own wrapper method, and that is not that difficult.

Thanks!
I'll close this issue.
