### ISSUE TITLE
Can SubscribeAwait's ConfigureAwait be set to default true?

### ISSUE THREAD

**Issue by TORISOUP** [Cysharp/R3#99]
In Unity, when SubscribeAwait is used with AwaitOperation.Sequential, if asynchronous processes are executed continuously, the second and subsequent processes will not be executed in the main thread.This problem can be avoided by specifying true for confitureAwait, but the default is false.

Can the default value be set to true or changed in the global settings?

---

(I added it later.)

This problem occurs when async/await during R3 is run with UniTask.

```cs
using Cysharp.Threading.Tasks;
using R3;
using UnityEngine;
using UnityEngine.UI;

namespace Samples.R3Sample
{
    public class SubscribeAwaitSample1 : MonoBehaviour
    {
        [SerializeField] private Button _goButton;

        private void Start()
        {
            _goButton.OnClickAsObservable()
                .SubscribeAwait(async (_, ct) =>
                    {
                        // After the second time, the section here may work in the thread pool
                        var time = Time.time;
                        while (Time.time - time < 1f)
                        {
                            transform.position += Vector3.forward * Time.deltaTime;
                            await UniTask.Yield(ct);
                        }
                    },
                    AwaitOperation.Sequential,
                    configureAwait: false)
                .AddTo(this);
        }
    }
}
```

**Comment by TORISOUP** [comment]
The same problem may involve SelectAwait/WhereAwait/ThrottleFirst/Last.

**Comment by neuecc** [comment]
Is this combined with the standard Task?
I honestly feel the incompatibility with Rx when it comes to processes dependent on `SynchronizationContext`.
If the internals of async/await are `UniTask`, then, even though it's async/await, it runs on the main thread, so perhaps it doesn't require as much attention.
If you are dealing with Tasks that clearly seem to run on the thread pool, I think it's more Rx-like (and also better for performance) to bring them back with `ObserveOn`, rather than using `SynchronizationContext`.
What do you think?

**Comment by neuecc** [comment]
details: https://twitter.com/toRisouP/status/1757437013253656888
Yes, unintended execution on the ThreadPool due to ValueTask is a problem.
I am aware of this and have been quite concerned about it, so I will look into it more closely.

**Comment by TORISOUP** [comment]
Sorry, I didn't have enough information.
The problem occurs when combining R3 and UniTask.

I think there is no problem in controlling the context with ObserveOn during standard Task operation.

**Comment by neuecc** [comment]
I've modified all async/await configureAwait default to true.
